Feature Account-setting and Onboarding
anand-veersa/pharmacord pull request #20
Opened 2023-04-24 08:27 UTC by ritikVeersa

2023-04-25 11:47 UTC, anand-veersa requested changes

2023-04-25 11:47 UTC, anand-veersa commented on src/app/app.component.scss
> +  height: 100%; //we will do things with padding.
use appropriate comments

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.html
> +          (click)="addFacility()"
directives first then class then attributes then events. this is the sequence. check other comp and fix everywhere

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.scss
> +        &-facilityFax,
use same class for all instead of creating new classes for each

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.scss
> +      border-radius: 8px;
use rem

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.scss
> +        border-bottom: 4px solid #ecedee;
use variables

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.scss
> +          color: #535353;
variables

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.ts
> +  // public Fax: string;
remove

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.ts
> +
add access identifiers to all methods. and add private methods at the end of the code

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.ts
> +    console.log(
remove

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.ts
> +    this.backToParentComponent.emit({ backBtnClicked: true });
use single method. action(back/next) {
here emit data based on back/next
}

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.ts
> +    //   const facility = {
remove

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +    <p class="text-x-bold text-large">{{ componentTitle }}</p>
use correct sequence

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +  <!-- accordians start here -->
correct spelling

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +          <!-- <app-custom-table [dataSource]="facilities" [columnSchema]="columnSchema"
remove

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +                      element.Address === undefined ? element : element.Address
use x === x??y instead

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +                "></tr>
correct accordion spelling everywhere

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +  <!-- <button mat-button (click)="openTempDialog()">Open Temp Modal</button> -->
remove

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +                element.Address === undefined ? element : element.Address
use nullish coal

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +      [isDisabled]="this.prescribersWithSelectedFacility.length === 0">
no need for === 0. use !x.length

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.scss
> +    // align-items: end;
remove

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.ts
> +  @Input() providersWithAllFacilities: Array<any> = [];
@input then @output then public then private properties

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.ts
> +  ngOnInit(): void {
add access identifier to each method in every file

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.ts
> +      // this.getUpdatedProviderDetails();
remove

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.ts
> +            // providerFacility = { ...providerFacility, isSelected: true };
remove

2023-04-25 11:47 UTC, anand-veersa commented on src/app/shared/components/forms/custom-select/custom-select.component.scss
> +//   height: 4rem;
remove

2023-04-25 11:47 UTC, anand-veersa commented on src/app/enrollment/pages/account-settings/account-settings.component.ts
> +    // Url: https://ext-api.pharmacord.com/portaldev/api/v1.0/portal/account/deleteProvider/386
remove\

2023-04-25 11:47 UTC, anand-veersa commented on src/app/enrollment/pages/account-settings/account-settings.component.ts
> +      //     const index2 = this.prescribersWithSelectedFacility[
rmove

2023-04-25 11:47 UTC, anand-veersa commented on src/app/enrollment/pages/account-settings/account-settings.component.ts
> +import {
remove all commented code add axccess identifiers to methods

2023-04-25 11:47 UTC, anand-veersa commented on src/app/enrollment/pages/account-settings/account-settings.component.html
> +        requirementFor="accountSetting"></app-add-facility>
move to top

2023-04-25 11:47 UTC, anand-veersa commented on src/app/enrollment/pages/account-settings/account-settings.component.html
> +        requirementFor="accountSetting">
move to top

2023-04-25 11:47 UTC, anand-veersa commented on src/app/core/interceptors/auth-interceptor.service.ts
> -      ProgramId: '500034',
use from env

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/registration.component.ts
> +    this.http
create a single json with different objects inside. and use single http instead of multiple calls

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/registration.component.scss
> +          .confirmAccountLastName,
use same class

2023-04-25 11:47 UTC, anand-veersa commented on src/app/auth/pages/registration/registration.component.scss
> +          border-radius: 10px;
rem

2023-04-25 12:21 UTC, Sa-So commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +                <th class="" mat-header-cell *matHeaderCellDef>
remove empty class

2023-04-26 07:28 UTC, ritikVeersa commented on src/app/app.component.scss
> +  height: 100%; //we will do things with padding.
removed

2023-04-26 07:30 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.scss
> +        border-bottom: 4px solid #ecedee;
used color-border-3 instead this, that was kind of similar

2023-04-26 07:32 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.scss
> +          color: #535353;
using color-sub-header ie similar

2023-04-26 07:42 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.ts
> +    console.log(
ALL consoles removed

2023-04-26 07:47 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +                <th class="" mat-header-cell *matHeaderCellDef>
done sir

2023-04-26 07:48 UTC, ritikVeersa commented on src/app/auth/pages/registration/registration.component.scss
> +          border-radius: 10px;
done

2023-04-26 07:51 UTC, ritikVeersa commented on src/app/core/interceptors/auth-interceptor.service.ts
> -      ProgramId: '500034',
Created Variable in Env

2023-04-27 07:58 UTC, ritikVeersa commented on src/app/auth/pages/registration/registration.component.ts
> +    this.http
All registration forms are shifted to one json named registration-forms.json

2023-04-28 06:25 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.ts
> +    this.backToParentComponent.emit({ backBtnClicked: true });
Done

2023-04-28 10:18 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.html
> +          (click)="addFacility()"
Done

2023-04-28 10:18 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.scss
> +        &-facilityFax,
No Need

2023-04-28 10:19 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.ts
> +  // public Fax: string;
done

2023-04-28 10:19 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.ts
> +
done

2023-04-28 10:20 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-facility/add-facility.component.ts
> +    //   const facility = {
Done

2023-04-28 10:23 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +  <!-- accordians start here -->
Done

2023-04-28 10:24 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +                "></tr>
Done

2023-04-28 10:24 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +  <!-- <button mat-button (click)="openTempDialog()">Open Temp Modal</button> -->
done

2023-04-28 10:26 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.scss
> +    // align-items: end;
done

2023-04-28 10:28 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.ts
> +  ngOnInit(): void {
Done

2023-04-28 10:49 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.ts
> +            // providerFacility = { ...providerFacility, isSelected: true };
removed

2023-04-28 10:53 UTC, ritikVeersa commented on src/app/enrollment/pages/account-settings/account-settings.component.ts
> +      //     const index2 = this.prescribersWithSelectedFacility[
done

2023-04-28 10:53 UTC, ritikVeersa commented on src/app/enrollment/pages/account-settings/account-settings.component.ts
> +import {
done

2023-04-28 10:53 UTC, ritikVeersa commented on src/app/enrollment/pages/account-settings/account-settings.component.html
> +        requirementFor="accountSetting"></app-add-facility>
done

2023-04-28 10:54 UTC, ritikVeersa commented on src/app/auth/pages/registration/registration.component.scss
> +          .confirmAccountLastName,
I think it's good so that when we develop for smaller screens it will be easy

2023-04-28 10:56 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +    <p class="text-x-bold text-large">{{ componentTitle }}</p>
unable to understand

2023-04-28 10:56 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.ts
> +  @Input() providersWithAllFacilities: Array<any> = [];
done

2023-04-28 10:57 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.ts
> +      // this.getUpdatedProviderDetails();
removed

2023-04-28 11:15 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +                      element.Address === undefined ? element : element.Address
Done

2023-04-28 11:16 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +      [isDisabled]="this.prescribersWithSelectedFacility.length === 0">
done

2023-04-28 11:16 UTC, ritikVeersa commented on src/app/auth/pages/registration/add-healthcare-provider/add-healthcare-provider.component.html
> +                element.Address === undefined ? element : element.Address
done

2023-05-01 06:32 UTC, anand-veersa approved these changes

2023-05-01 06:32 UTC, merged